# vim:set ft=tmux:

# --> Sonokai (Espresso)

# Background shades
set -ogq @snk_black "#1f1e1c"
set -ogq @snk_bg_dim "#242120"
set -ogq @snk_bg0 "#312c2b"
set -ogq @snk_bg1 "#393230"
set -ogq @snk_bg2 "#413937"
set -ogq @snk_bg3 "#49403c"
set -ogq @snk_bg4 "#4e433f"

# Diff/accent backgrounds
set -ogq @snk_bg_red "#55393d"
set -ogq @snk_bg_yellow "#4e432f"
set -ogq @snk_bg_green "#394634"
set -ogq @snk_bg_blue "#354157"
set -ogq @snk_bg_purple "#463e4f"

# Foreground
set -ogq @snk_fg "#e4e3e1"

# Accent colors
set -ogq @snk_red "#f86882"
set -ogq @snk_orange "#f08d71"
set -ogq @snk_yellow "#f0c66f"
set -ogq @snk_green "#a6cd77"
set -ogq @snk_blue "#81d0c9"
set -ogq @snk_purple "#9fa0e1"

# Filled (bright) variants
set -ogq @snk_filled_red "#fd6883"
set -ogq @snk_filled_green "#adda78"
set -ogq @snk_filled_blue "#85dad2"

# Greys
set -ogq @snk_grey "#90817b"
set -ogq @snk_grey_dim "#6a5e59"
