# vim:set ft=tmux:

# --> Sonokai (Shusia)

# Background shades
set -ogq @snk_black "#1a181a"
set -ogq @snk_bg_dim "#211f21"
set -ogq @snk_bg0 "#2d2a2e"
set -ogq @snk_bg1 "#37343a"
set -ogq @snk_bg2 "#3b383e"
set -ogq @snk_bg3 "#423f46"
set -ogq @snk_bg4 "#49464e"

# Diff/accent backgrounds
set -ogq @snk_bg_red "#55393d"
set -ogq @snk_bg_yellow "#4e432f"
set -ogq @snk_bg_green "#394634"
set -ogq @snk_bg_blue "#354157"
set -ogq @snk_bg_purple "#463e4f"

# Foreground
set -ogq @snk_fg "#e3e1e4"

# Accent colors
set -ogq @snk_red "#f85e84"
set -ogq @snk_orange "#ef9062"
set -ogq @snk_yellow "#e5c463"
set -ogq @snk_green "#9ecd6f"
set -ogq @snk_blue "#7accd7"
set -ogq @snk_purple "#ab9df2"

# Filled (bright) variants
set -ogq @snk_filled_red "#ff6188"
set -ogq @snk_filled_green "#a8d475"
set -ogq @snk_filled_blue "#85d6e3"

# Greys
set -ogq @snk_grey "#848089"
set -ogq @snk_grey_dim "#605d68"
