# vim:set ft=tmux:

# --> Sonokai (Maia)
set -ogq @thm_bg "#273136"
set -ogq @thm_fg "#e1e2e3"

# Colors
set -ogq @thm_rosewater "#f3a96a"
set -ogq @thm_flamingo "#f76c7c"
set -ogq @thm_pink "#baa0f8"
set -ogq @thm_mauve "#baa0f8"
set -ogq @thm_red "#f76c7c"
set -ogq @thm_maroon "#ff6d7e"
set -ogq @thm_peach "#f3a96a"
set -ogq @thm_yellow "#e3d367"
set -ogq @thm_green "#9cd57b"
set -ogq @thm_teal "#78cee9"
set -ogq @thm_sky "#78cee9"
set -ogq @thm_sapphire "#78cee9"
set -ogq @thm_blue "#78cee9"
set -ogq @thm_lavender "#baa0f8"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#82878b"
set -ogq @thm_subtext_0 "#82878b"
set -ogq @thm_overlay_2 "#82878b"
set -ogq @thm_overlay_1 "#55626d"
set -ogq @thm_overlay_0 "#414b53"
set -ogq @thm_surface_2 "#3a444b"
set -ogq @thm_surface_1 "#353f46"
set -ogq @thm_surface_0 "#313b42"
set -ogq @thm_mantle "#21282c"
set -ogq @thm_crust "#1c1e1f"
