# vim:set ft=tmux:

# --> Sonokai (Default)

# Background shades
set -ogq @snk_black "#181819"
set -ogq @snk_bg_dim "#222327"
set -ogq @snk_bg0 "#2c2e34"
set -ogq @snk_bg1 "#33353f"
set -ogq @snk_bg2 "#363944"
set -ogq @snk_bg3 "#3b3e48"
set -ogq @snk_bg4 "#414550"

# Diff/accent backgrounds
set -ogq @snk_bg_red "#55393d"
set -ogq @snk_bg_yellow "#4e432f"
set -ogq @snk_bg_green "#394634"
set -ogq @snk_bg_blue "#354157"
set -ogq @snk_bg_purple "#463e4f"

# Foreground
set -ogq @snk_fg "#e2e2e3"

# Accent colors
set -ogq @snk_red "#fc5d7c"
set -ogq @snk_orange "#f39660"
set -ogq @snk_yellow "#e7c664"
set -ogq @snk_green "#9ed072"
set -ogq @snk_blue "#76cce0"
set -ogq @snk_purple "#b39df3"

# Filled (bright) variants
set -ogq @snk_filled_red "#ff6077"
set -ogq @snk_filled_green "#a7df78"
set -ogq @snk_filled_blue "#85e0f0"

# Greys
set -ogq @snk_grey "#7f8490"
set -ogq @snk_grey_dim "#595f6f"
