# vim:set ft=tmux:

# --> Sonokai (Default)
set -ogq @thm_bg "#2c2e34"
set -ogq @thm_fg "#e2e2e3"

# Colors
set -ogq @thm_rosewater "#f39660"
set -ogq @thm_flamingo "#fc5d7c"
set -ogq @thm_pink "#b39df3"
set -ogq @thm_mauve "#b39df3"
set -ogq @thm_red "#fc5d7c"
set -ogq @thm_maroon "#ff6077"
set -ogq @thm_peach "#f39660"
set -ogq @thm_yellow "#e7c664"
set -ogq @thm_green "#9ed072"
set -ogq @thm_teal "#76cce0"
set -ogq @thm_sky "#76cce0"
set -ogq @thm_sapphire "#76cce0"
set -ogq @thm_blue "#76cce0"
set -ogq @thm_lavender "#b39df3"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#7f8490"
set -ogq @thm_subtext_0 "#7f8490"
set -ogq @thm_overlay_2 "#7f8490"
set -ogq @thm_overlay_1 "#595f6f"
set -ogq @thm_overlay_0 "#414550"
set -ogq @thm_surface_2 "#3b3e48"
set -ogq @thm_surface_1 "#363944"
set -ogq @thm_surface_0 "#33353f"
set -ogq @thm_mantle "#222327"
set -ogq @thm_crust "#181819"
