# vim:set ft=tmux:

# --> Sonokai (Andromeda)
set -ogq @thm_bg "#2b2d3a"
set -ogq @thm_fg "#e1e3e4"

# Colors
set -ogq @thm_rosewater "#f89860"
set -ogq @thm_flamingo "#fb617e"
set -ogq @thm_pink "#bb97ee"
set -ogq @thm_mauve "#bb97ee"
set -ogq @thm_red "#fb617e"
set -ogq @thm_maroon "#ff6188"
set -ogq @thm_peach "#f89860"
set -ogq @thm_yellow "#edc763"
set -ogq @thm_green "#9ed06c"
set -ogq @thm_teal "#6dcae8"
set -ogq @thm_sky "#6dcae8"
set -ogq @thm_sapphire "#6dcae8"
set -ogq @thm_blue "#6dcae8"
set -ogq @thm_lavender "#bb97ee"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#7e8294"
set -ogq @thm_subtext_0 "#7e8294"
set -ogq @thm_overlay_2 "#7e8294"
set -ogq @thm_overlay_1 "#5a5e7a"
set -ogq @thm_overlay_0 "#3f445b"
set -ogq @thm_surface_2 "#393e53"
set -ogq @thm_surface_1 "#363a4e"
set -ogq @thm_surface_0 "#333648"
set -ogq @thm_mantle "#252630"
set -ogq @thm_crust "#181a1c"
