# vim:set ft=tmux:

# --> Sonokai (Atlantis)
set -ogq @thm_bg "#2a2f38"
set -ogq @thm_fg "#e1e3e4"

# Colors
set -ogq @thm_rosewater "#f69c5e"
set -ogq @thm_flamingo "#ff6578"
set -ogq @thm_pink "#ba9cf3"
set -ogq @thm_mauve "#ba9cf3"
set -ogq @thm_red "#ff6578"
set -ogq @thm_maroon "#ff6d7e"
set -ogq @thm_peach "#f69c5e"
set -ogq @thm_yellow "#eacb64"
set -ogq @thm_green "#9dd274"
set -ogq @thm_teal "#72cce8"
set -ogq @thm_sky "#72cce8"
set -ogq @thm_sapphire "#72cce8"
set -ogq @thm_blue "#72cce8"
set -ogq @thm_lavender "#ba9cf3"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#828a9a"
set -ogq @thm_subtext_0 "#828a9a"
set -ogq @thm_overlay_2 "#828a9a"
set -ogq @thm_overlay_1 "#5a6477"
set -ogq @thm_overlay_0 "#424b5b"
set -ogq @thm_surface_2 "#3d4455"
set -ogq @thm_surface_1 "#373c4b"
set -ogq @thm_surface_0 "#333846"
set -ogq @thm_mantle "#24272e"
set -ogq @thm_crust "#181a1c"
