# vim:set ft=tmux:

# --> Sonokai (Espresso)
set -ogq @thm_bg "#312c2b"
set -ogq @thm_fg "#e4e3e1"

# Colors
set -ogq @thm_rosewater "#f08d71"
set -ogq @thm_flamingo "#f86882"
set -ogq @thm_pink "#9fa0e1"
set -ogq @thm_mauve "#9fa0e1"
set -ogq @thm_red "#f86882"
set -ogq @thm_maroon "#fd6883"
set -ogq @thm_peach "#f08d71"
set -ogq @thm_yellow "#f0c66f"
set -ogq @thm_green "#a6cd77"
set -ogq @thm_teal "#81d0c9"
set -ogq @thm_sky "#81d0c9"
set -ogq @thm_sapphire "#81d0c9"
set -ogq @thm_blue "#81d0c9"
set -ogq @thm_lavender "#9fa0e1"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#90817b"
set -ogq @thm_subtext_0 "#90817b"
set -ogq @thm_overlay_2 "#90817b"
set -ogq @thm_overlay_1 "#6a5e59"
set -ogq @thm_overlay_0 "#4e433f"
set -ogq @thm_surface_2 "#49403c"
set -ogq @thm_surface_1 "#413937"
set -ogq @thm_surface_0 "#393230"
set -ogq @thm_mantle "#242120"
set -ogq @thm_crust "#1f1e1c"
