# vim:set ft=tmux:

# --> Sonokai (Shusia)
set -ogq @thm_bg "#2d2a2e"
set -ogq @thm_fg "#e3e1e4"

# Colors
set -ogq @thm_rosewater "#ef9062"
set -ogq @thm_flamingo "#f85e84"
set -ogq @thm_pink "#ab9df2"
set -ogq @thm_mauve "#ab9df2"
set -ogq @thm_red "#f85e84"
set -ogq @thm_maroon "#ff6188"
set -ogq @thm_peach "#ef9062"
set -ogq @thm_yellow "#e5c463"
set -ogq @thm_green "#9ecd6f"
set -ogq @thm_teal "#7accd7"
set -ogq @thm_sky "#7accd7"
set -ogq @thm_sapphire "#7accd7"
set -ogq @thm_blue "#7accd7"
set -ogq @thm_lavender "#ab9df2"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#848089"
set -ogq @thm_subtext_0 "#848089"
set -ogq @thm_overlay_2 "#848089"
set -ogq @thm_overlay_1 "#605d68"
set -ogq @thm_overlay_0 "#49464e"
set -ogq @thm_surface_2 "#423f46"
set -ogq @thm_surface_1 "#3b383e"
set -ogq @thm_surface_0 "#37343a"
set -ogq @thm_mantle "#211f21"
set -ogq @thm_crust "#1a181a"
