# vim:set ft=tmux:

# --> Sonokai (Maia)

# Background shades
set -ogq @snk_black "#1c1e1f"
set -ogq @snk_bg_dim "#21282c"
set -ogq @snk_bg0 "#273136"
set -ogq @snk_bg1 "#313b42"
set -ogq @snk_bg2 "#353f46"
set -ogq @snk_bg3 "#3a444b"
set -ogq @snk_bg4 "#414b53"

# Diff/accent backgrounds
set -ogq @snk_bg_red "#55393d"
set -ogq @snk_bg_yellow "#4e432f"
set -ogq @snk_bg_green "#394634"
set -ogq @snk_bg_blue "#354157"
set -ogq @snk_bg_purple "#463e4f"

# Foreground
set -ogq @snk_fg "#e1e2e3"

# Accent colors
set -ogq @snk_red "#f76c7c"
set -ogq @snk_orange "#f3a96a"
set -ogq @snk_yellow "#e3d367"
set -ogq @snk_green "#9cd57b"
set -ogq @snk_blue "#78cee9"
set -ogq @snk_purple "#baa0f8"

# Filled (bright) variants
set -ogq @snk_filled_red "#ff6d7e"
set -ogq @snk_filled_green "#a6dd82"
set -ogq @snk_filled_blue "#88d8f1"

# Greys
set -ogq @snk_grey "#82878b"
set -ogq @snk_grey_dim "#55626d"
